addons: # get google-chrome-stable
  chrome: beta
language: node_js
node_js:
  - "8.1"
install:
  - npm install
script:
  - npm run unit-test && npm run integration-test

# the following is required for sharp install
# can remove after sharp dependency is removed
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
